apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml


images:
- name: goserver
  newName: sancrisxa/gitopsfc
  newTag: 47256f3f8b33a31f6b9520660d7115835cf29426
